var dropdown_options = [
  { value: "Afghanistan", text: "Taliban"},
  { value: "Afghanistan", text: "Khorasan Chapter of the Islamic State"},
  { value: "Afghanistan", text: "Haqqani Network"},
  { value: "Afghanistan", text: "Hizb-I-Islami"},
  { value: "Afghanistan", text: "Al-Qaida"},
  { value: "Albania", text: "Muslim extremists"},
  { value: "Algeria", text: "Algerian Islamic Extremists"},
  { value: "Algeria", text: "Armed Islamic Group (GIA)"},
  { value: "Algeria", text: "Salafist Group for Preaching and Fighting (GSPC)"},
  { value: "Algeria", text: "Al-Qaida in the Islamic Maghreb (AQIM)"},
  { value: "Algeria", text: "Islamic Salvation Front (FIS)"},
  { value: "Angola", text: "National Union for the Total Independence of Angola (UNITA)"},
  { value: "Angola", text: "Front for the Liberation of the Enclave of Cabinda (FLEC)"},
  { value: "Angola", text: "Popular Movement for the Liberation of Angola"},
  { value: "Angola", text: "Front for the Liberation of Cabinda / Cabinda Armed Forces (FLEC-FAC)"},
  { value: "Angola", text: "Angola Rebels"},
  { value: "Argentina", text: "Montoneros (Argentina)"},
  { value: "Argentina", text: "Ejercito Revolucionaria del Pueblo (ERP) (Argentina)"},
  { value: "Argentina", text: "People's Revolutionary Organization"},
  { value: "Argentina", text: "Peronist Armed Forces (FAP)"},
  { value: "Argentina", text: "Argentine Anticommunist Alliance (AAA)"},
  { value: "Armenia", text: "Armenian Guerrillas"},
  { value: "Armenia", text: "Armenian militants"},
  { value: "Armenia", text: "Armenian nationalists"},
  { value: "Armenia", text: "Sasna Tsrer"},
  { value: "Australia", text: "Jihadi-inspired extremists"},
  { value: "Australia", text: "Croatian Nationalists"},
  { value: "Australia", text: "Informal Anarchist Federation"},
  { value: "Australia", text: "Extortionists"},
  { value: "Australia", text: "Anarchists"},
  { value: "Austria", text: "Neo-Nazi extremists"},
  { value: "Austria", text: "Kurdistan Workers' Party (PKK)"},
  { value: "Austria", text: "Right-wing extremists"},
  { value: "Austria", text: "Justice Commandos for the Armenian Genocide"},
  { value: "Austria", text: "Waltraud Boock Group"},
  { value: "Azerbaijan", text: "Azerbaijan Guerrillas"},
  { value: "Azerbaijan", text: "Forest Brothers"},
  { value: "Azerbaijan", text: "Armenian Guerrillas"},
  { value: "Azerbaijan", text: "Opposition Group"},
  { value: "Azerbaijan", text: "Sandval (union) Movement"},
  { value: "Bahrain", text: "Al-Ashtar Brigades"},
  { value: "Bahrain", text: "Hezbollah"},
  { value: "Bahrain", text: "February 14th Movement"},
  { value: "Bahrain", text: "Islamic State of Iraq and the Levant (ISIL)"},
  { value: "Bahrain", text: "Al-Haydariyah Battalion"},
  { value: "Bangladesh", text: "Pro Hartal Activists"},
  { value: "Bangladesh", text: "Bangladesh Nationalist Party (BNP)"},
  { value: "Bangladesh", text: "Opposition Group"},
  { value: "Bangladesh", text: "Jamaat-E-Islami (Bangladesh)"},
  { value: "Bangladesh", text: "Shanti Bahini - Peace Force"},
  { value: "Barbados", text: "Coordination of the United Revolutionary Organization (CORU)"},
  { value: "Belarus", text: "Friends of Freedom"},
  { value: "Belarus", text: "Belarusian Liberation Army"},
  { value: "Belgium", text: "Communist Combattant Cells (CCC) (Belgium)"},
  { value: "Belgium", text: "Kurdistan Workers' Party (PKK)"},
  { value: "Belgium", text: "International Revolutionary Action Group (GARI)"},
  { value: "Belgium", text: "Justice Commandos for the Armenian Genocide"},
  { value: "Belgium", text: "Animal Liberation Front (ALF)"},
  { value: "Bhutan", text: "The United Revolutionary Front of Bhutan"},
  { value: "Bhutan", text: "National Democratic Front of Bodoland (NDFB)"},
  { value: "Bolivia", text: "Tupac Katari Guerrilla Army (EGTK)"},
  { value: "Bolivia", text: "Bolivian Socialist Falange"},
  { value: "Bolivia", text: "Political Activists"},
  { value: "Bolivia", text: "Shining Path (SL)"},
  { value: "Bolivia", text: "Zarate Willka Armed Forces of Liberation"},
  { value: "Bosnia and Herzegovina", text: "Serbian guerrillas"},
  { value: "Bosnia and Herzegovina", text: "Muslim extremists"},
  { value: "Bosnia and Herzegovina", text: "Bosnian Serbs"},
  { value: "Bosnia and Herzegovina", text: "Croatians"},
  { value: "Bosnia and Herzegovina", text: "Serbian irregulars"},
  { value: "Botswana", text: "African National Congress (South Africa)"},
  { value: "Brazil", text: "Death Squad"},
  { value: "Brazil", text: "Landless Peasants' Movement (MST)"},
  { value: "Brazil", text: "Popular Revolutionary Vanguard (VPR)"},
  { value: "Brazil", text: "Brazilian Anti-Communist Alliance (AAB)"},
  { value: "Brazil", text: "Communist Hunters Command (CCC)"},
  { value: "Bulgaria", text: "Anti-Muslim extremists"},
  { value: "Bulgaria", text: "Armenian Secret Army for the Liberation of Armenia"},
  { value: "Bulgaria", text: "Elos security firm"},
  { value: "Bulgaria", text: "Hezbollah"},
  { value: "Bulgaria", text: "Justice Commandos for the Armenian Genocide"},
  { value: "Burkina Faso", text: "Al-Qaida in the Islamic Maghreb (AQIM)"},
  { value: "Burkina Faso", text: "Islamic State in the Greater Sahara (ISGS)"},
  { value: "Burkina Faso", text: "Al-Mua'qi'oon Biddam Brigade (Those who Sign with Blood)"},
  { value: "Burkina Faso", text: "Ansar al-Islam (Burkina Faso)"},
  { value: "Burkina Faso", text: "Boko Haram"},
  { value: "Burundi", text: "Hutu extremists"},
  { value: "Burundi", text: "Party for the Liberation of the Hutu People (PALIPEHUTU)"},
  { value: "Burundi", text: "National Liberation Front (FNL) (Burundi)"},
  { value: "Burundi", text: "Tutsi"},
  { value: "Burundi", text: "National Council for Defense of Democracy (NCDD)"},
  { value: "Cambodia", text: "Khmer Rouge"},
  { value: "Cambodia", text: "Cambodian Freedom Fighters (CFF)"},
  { value: "Cambodia", text: "Cambodian People's Party (CPP)"},
  { value: "Cambodia", text: "Gunmen"},
  { value: "Cambodia", text: "National United Front for an Independent, Neutral, Peaceful, and Cooperative Cambodia (FUNCINPEC)"},
  { value: "Cameroon", text: "Boko Haram"},
  { value: "Cameroon", text: "Democratic Front of the Central African People (FDPC)"},
  { value: "Cameroon", text: "Africa Marine Commando"},
  { value: "Cameroon", text: "Kotoko Tribal Group"},
  { value: "Cameroon", text: "Seleka"},
  { value: "Canada", text: "Armenian Secret Army for the Liberation of Armenia"},
  { value: "Canada", text: "Army of God"},
  { value: "Canada", text: "Jihadi-inspired extremists"},
  { value: "Canada", text: "Animal Liberation Front (ALF)"},
  { value: "Canada", text: "Black September"},
  { value: "Central African Republic", text: "Anti-Balaka Militia"},
  { value: "Central African Republic", text: "Lord's Resistance Army (LRA)"},
  { value: "Central African Republic", text: "Seleka"},
  { value: "Central African Republic", text: "Convention of Patriots for Justice and Peace"},
  { value: "Central African Republic", text: "Fulani extremists"},
  { value: "Chad", text: "Boko Haram"},
  { value: "Chad", text: "United Front for Democratic Change (FUC)"},
  { value: "Chad", text: "National Alliance (Chad)"},
  { value: "Chad", text: "Union of Forces for Democracy and Development (UFDD)"},
  { value: "Chad", text: "Rebels"},
  { value: "Chile", text: "Manuel Rodriguez Patriotic Front (FPMR)"},
  { value: "Chile", text: "Movement of the Revolutionary Left (MIR) (Chile)"},
  { value: "Chile", text: "United Popular Action Movement"},
  { value: "Chile", text: "Mapuche activists"},
  { value: "Chile", text: "Anarchists"},
  { value: "China", text: "Uighur Separatists"},
  { value: "China", text: "Eastern Turkistan Islamic Movement (ETIM)"},
  { value: "China", text: "Kachin Independence Army (KIA)"},
  { value: "China", text: "Koreans"},
  { value: "China", text: "Muslim Separatists"},
  { value: "Colombia", text: "Revolutionary Armed Forces of Colombia (FARC)"},
  { value: "Colombia", text: "National Liberation Army of Colombia (ELN)"},
  { value: "Colombia", text: "M-19 (Movement of April 19)"},
  { value: "Colombia", text: "Narco-Terrorists"},
  { value: "Colombia", text: "Popular Liberation Army (EPL)"},
  { value: "Comoros", text: "Separatists"},
  { value: "Comoros", text: "Rebel Military Unit"},
  { value: "Costa Rica", text: "Coordination of the United Revolutionary Organization (CORU)"},
  { value: "Costa Rica", text: "Student Front of the People"},
  { value: "Costa Rica", text: "Revolutionary Commandos of Solidarity"},
  { value: "Costa Rica", text: "Sandinista National Liberation Front (FSLN)"},
  { value: "Costa Rica", text: "Carlos Echeverria commando group"},
  { value: "Croatia", text: "Serbian extremists"},
  { value: "Croatia", text: "Serbian guerrillas"},
  { value: "Croatia", text: "Serbian Nationalists"},
  { value: "Croatia", text: "Al-Gama'at al-Islamiyya (IG)"},
  { value: "Croatia", text: "Croatian Militia"},
  { value: "Cuba", text: "Raul Ernesto Cruz Leon, Salvadorian"},
  { value: "Cuba", text: "Counter-revolutionaries"},
  { value: "Cuba", text: "Cubans seeking escape from Cuba"},
  { value: "Cuba", text: "National Democratic Party"},
  { value: "Cyprus", text: "Cyprus Turkish People's Movement"},
  { value: "Cyprus", text: "Hezbollah"},
  { value: "Cyprus", text: "National Organization of Cypriot Fighters (EOKA)"},
  { value: "Cyprus", text: "Black September"},
  { value: "Cyprus", text: "Eagles of the Palestinian Revolution"},
  { value: "Czech Republic", text: "Neo-Nazi extremists"},
  { value: "Czech Republic", text: "Revolutionary Cells Network (SRN)"},
  { value: "Czech Republic", text: "Neo-Fascists"},
  { value: "Czech Republic", text: "Proletarian Solidarity"},
  { value: "Czechoslovakia", text: "Neo-Nazi extremists"},
  { value: "Czechoslovakia", text: "Skinhead group"},
  { value: "Democratic Republic of the Congo", text: "Allied Democratic Forces (ADF)"},
  { value: "Democratic Republic of the Congo", text: "Lord's Resistance Army (LRA)"},
  { value: "Democratic Republic of the Congo", text: "Democratic Front for the Liberation of Rwanda (FDLR)"},
  { value: "Democratic Republic of the Congo", text: "Mayi Mayi"},
  { value: "Democratic Republic of the Congo", text: "Patriotic Resistance Front in Ituri (FRPI)"},
  { value: "Denmark", text: "Anarchists"},
  { value: "Denmark", text: "Armenian Secret Army for the Liberation of Armenia"},
  { value: "Denmark", text: "Jihadi-inspired extremists"},
  { value: "Denmark", text: "Hezbollah"},
  { value: "Denmark", text: "Ninth of June Organization"},
  { value: "Djibouti", text: "Front for the Restoration of Unity and Democracy"},
  { value: "Djibouti", text: "Afar rebels"},
  { value: "Djibouti", text: "Al-Shabaab"},
  { value: "Djibouti", text: "Extremist Nat'list Group"},
  { value: "Dominica", text: "Anti-Government Group"},
  { value: "Dominican Republic", text: "Maximiliano Gomez Revolutionary Brigade"},
  { value: "Dominican Republic", text: "Popular Liberation Resistance Force"},
  { value: "Dominican Republic", text: "Strikers"},
  { value: "Dominican Republic", text: "Dominican Popular Movement (MPD)"},
  { value: "Dominican Republic", text: "Tony El Pelou Band"},
  { value: "East Germany (GDR)", text: "Extraparliamentary Opposition (APO)"},
  { value: "East Germany (GDR)", text: "Internationalist Cells"},
  { value: "East Germany (GDR)", text: "Red Army Faction (RAF)"},
  { value: "East Germany (GDR)", text: "Neo-Nazi extremists"},
  { value: "East Germany (GDR)", text: "2nd of June Movement"},
  { value: "East Timor", text: "Pro-Indonesia extremists"},
  { value: "Ecuador", text: "Alfaro Vive"},
  { value: "Ecuador", text: "Montoneros Patria Libre"},
  { value: "Ecuador", text: "People's Revolutionary Militias (MRP)"},
  { value: "Ecuador", text: "Colombian Guerrillas"},
  { value: "Ecuador", text: "National Liberation Army (Ecuador)"},
  { value: "Egypt", text: "Sinai Province of the Islamic State"},
  { value: "Egypt", text: "Al-Gama'at al-Islamiyya (IG)"},
  { value: "Egypt", text: "Muslim extremists"},
  { value: "Egypt", text: "Ansar Bayt al-Maqdis (Ansar Jerusalem)"},
  { value: "Egypt", text: "Muslim Militants"},
  { value: "El Salvador", text: "Farabundo Marti National Liberation Front (FMLN)"},
  { value: "El Salvador", text: "People's Liberation Forces (FPL)"},
  { value: "El Salvador", text: "People's Revolutionary Army (ERP) (El Salvador)"},
  { value: "El Salvador", text: "Death Squad"},
  { value: "El Salvador", text: "Armed Forces of National Resistance (FARN)"},
  { value: "Equatorial Guinea", text: "Movement for the Emancipation of the Niger Delta (MEND)"},
  { value: "Eritrea", text: "Democratic Movement for the Liberation of the Eritrean Kunamas (DMLEK)"},
  { value: "Eritrea", text: "Eritrean Salvation Front (ESF)"},
  { value: "Eritrea", text: "Nomadic AFARS"},
  { value: "Eritrea", text: "Red Sea Afar Democratic Organization (RSADO)"},
  { value: "Estonia", text: "Fatherland"},
  { value: "Estonia", text: "Kaitseliit Paramiltary Group"},
  { value: "Ethiopia", text: "Eritrean Liberation Front"},
  { value: "Ethiopia", text: "Murle Tribe"},
  { value: "Ethiopia", text: "Tigray Peoples Liberation Front (TPLF)"},
  { value: "Ethiopia", text: "Al-Shabaab"},
  { value: "Ethiopia", text: "Ogaden National Liberation Front (ONLF)"},
  { value: "Falkland Islands", text: "Artigas-Giachino Command"},
  { value: "Fiji", text: "Anti-Government extremists"},
  { value: "Fiji", text: "Christian extremists"},
  { value: "Fiji", text: "Rebel Military Unit"},
  { value: "Finland", text: "Animal Liberation Front (ALF)"},
  { value: "Finland", text: "Anti-Immigrant extremists"},
  { value: "Finland", text: "Kurdistan Workers' Party (PKK)"},
  { value: "Finland", text: "Neo-Fascists"},
  { value: "France", text: "Corsican National Liberation Front (FLNC)"},
  { value: "France", text: "Corsican National Liberation Front- Historic Channel"},
  { value: "France", text: "Separatists"},
  { value: "France", text: "Resistenza"},
  { value: "France", text: "Corsican Separatists"},
  { value: "French Guiana", text: "Caribbean Revolutionary Alliance (ARC)"},
  { value: "French Guiana", text: "Separatists"},
  { value: "French Guiana", text: "Farmers"},
  { value: "French Polynesia", text: "Anti-Nuclear extremists"},
  { value: "Gabon", text: "Convention of Liberal Reformers (CLR)"},
  { value: "Georgia", text: "South Ossetian Separatists"},
  { value: "Georgia", text: "Supporters of Ex-President Gamsakhurdial"},
  { value: "Georgia", text: "Abkhazian Separatists"},
  { value: "Georgia", text: "Georgian extremists"},
  { value: "Georgia", text: "Algeisk Wolves"},
  { value: "Germany", text: "Neo-Nazi extremists"},
  { value: "Germany", text: "Kurdistan Workers' Party (PKK)"},
  { value: "Germany", text: "National Socialist Underground"},
  { value: "Germany", text: "Right-wing extremists"},
  { value: "Germany", text: "Jihadi-inspired extremists"},
  { value: "Ghana", text: "Farighan"},
  { value: "Ghana", text: "New Patriotic Party (NPP)"},
  { value: "Ghana", text: "Al-Sunni muslim sect"},
  { value: "Ghana", text: "Ningo Tribe"},
  { value: "Greece", text: "November 17 Revolutionary Organization (N17RO)"},
  { value: "Greece", text: "Revolutionary People's Struggle (ELA)"},
  { value: "Greece", text: "Conspiracy of Cells of Fire"},
  { value: "Greece", text: "Anarchists"},
  { value: "Greece", text: "Revolutionary Struggle"},
  { value: "Guadeloupe", text: "Caribbean Revolutionary Alliance (ARC)"},
  { value: "Guadeloupe", text: "Armed Group for the Liberation of Guadeloupe (GLAG)"},
  { value: "Guadeloupe", text: "Guadeloupe Liberation Army"},
  { value: "Guadeloupe", text: "Separatists"},
  { value: "Guatemala", text: "Guerrilla Army of the Poor (EGP)"},
  { value: "Guatemala", text: "Revolutionary Organization of People in Arms (ORPA)"},
  { value: "Guatemala", text: "Guatemalan National Revolutionary Unity (URNG)"},
  { value: "Guatemala", text: "Death Squad"},
  { value: "Guatemala", text: "Rebel Armed Forces of Guatemala (FAR)"},
  { value: "Guinea", text: "Rebels"},
  { value: "Guinea", text: "Revolutionary United Front (RUF)"},
  { value: "Guinea", text: "Allied Democratic Forces of Guinea (RDFG)"},
  { value: "Guinea", text: "National Patriotic Front of Liberia (NPFL)"},
  { value: "Guinea", text: "U/I Liberian Gunmen"},
  { value: "Guyana", text: "Gunmen"},
  { value: "Guyana", text: "People's Temple"},
  { value: "Guyana", text: "Unk (men in army uniforms with arms and gas masks)"},
  { value: "Guyana", text: "Working People's Alliance (WPA)"},
  { value: "Haiti", text: "Aristide supporters"},
  { value: "Haiti", text: "Armed People"},
  { value: "Haiti", text: "Cannibal Army"},
  { value: "Haiti", text: "Protesters"},
  { value: "Haiti", text: "Revolutionary Front for Hatian Advancement and Progress (FRAPH)"},
  { value: "Honduras", text: "Lorenzo Zelaya Revolutionary Front (LZRF)"},
  { value: "Honduras", text: "Patriotic Morazanista Front (FPM)"},
  { value: "Honduras", text: "Cinchoneros Popular Liberation Movement"},
  { value: "Honduras", text: "Farabundo Marti National Liberation Front (FMLN)"},
  { value: "Honduras", text: "Nicaraguan Democratic Force (FDN)"},
  { value: "Hong Kong", text: "Pirates"},
  { value: "Hong Kong", text: "Chinese Pirates"},
  { value: "Hong Kong", text: "Vietnamese Detainees"},
  { value: "Hungary", text: "Armenian Secret Army for the Liberation of Armenia"},
  { value: "Hungary", text: "Hungarian Skin Head Group"},
  { value: "Hungary", text: "Movement for the Protection of Jerusalem"},
  { value: "Hungary", text: "Serbian Gangsters"},
  { value: "Iceland", text: "Sea Shepherd Conservation Society"},
  { value: "India", text: "Communist Party of India - Maoist (CPI-Maoist)"},
  { value: "India", text: "Maoists"},
  { value: "India", text: "Sikh Extremists"},
  { value: "India", text: "United Liberation Front of Assam (ULFA)"},
  { value: "India", text: "National Democratic Front of Bodoland (NDFB)"},
  { value: "Indonesia", text: "Free Aceh Movement (GAM)"},
  { value: "Indonesia", text: "Jemaah Islamiya (JI)"},
  { value: "Indonesia", text: "Muslim Militants"},
  { value: "Indonesia", text: "Free Papua Movement (OPM-Organisasi Papua Merdeka)"},
  { value: "Indonesia", text: "Mujahidin Indonesia Timur (MIT)"},
  { value: "International", text: "Al-Qaida"},
  { value: "Iran", text: "Mujahedin-e Khalq (MEK)"},
  { value: "Iran", text: "Arab Separatists"},
  { value: "Iran", text: "Forqan Group"},
  { value: "Iran", text: "Counter-revolutionaries"},
  { value: "Iran", text: "Armenian Secret Army for the Liberation of Armenia"},
  { value: "Iraq", text: "Islamic State of Iraq and the Levant (ISIL)"},
  { value: "Iraq", text: "Al-Qaida in Iraq"},
  { value: "Iraq", text: "Islamic State of Iraq (ISI)"},
  { value: "Iraq", text: "Asa'ib Ahl al-Haqq"},
  { value: "Iraq", text: "Gunmen"},
  { value: "Ireland", text: "Irish Republican Army (IRA)"},
  { value: "Ireland", text: "Ulster Freedom Fighters (UFF)"},
  { value: "Ireland", text: "Ulster Volunteer Force (UVF)"},
  { value: "Ireland", text: "Irish National Liberation Army (INLA)"},
  { value: "Ireland", text: "Dissident Republicans"},
  { value: "Israel", text: "Palestinians"},
  { value: "Israel", text: "Hamas (Islamic Resistance Movement)"},
  { value: "Israel", text: "Palestinian Islamic Jihad (PIJ)"},
  { value: "Israel", text: "Palestinian Extremists"},
  { value: "Israel", text: "Al-Aqsa Martyrs Brigade"},
  { value: "Italy", text: "Red Brigades"},
  { value: "Italy", text: "Prima Linea"},
  { value: "Italy", text: "Armed Proletarian Nuclei (NAP)"},
  { value: "Italy", text: "Armenian Secret Army for the Liberation of Armenia"},
  { value: "Italy", text: "Baader-Meinhof Group"},
  { value: "Ivory Coast", text: "Gbagbo Loyalists"},
  { value: "Ivory Coast", text: "Federation of Students and Scholars of Cote d'Ivoire (FESCI)"},
  { value: "Ivory Coast", text: "Al-Qaida in the Islamic Maghreb (AQIM)"},
  { value: "Ivory Coast", text: "Ivorian Popular Front"},
  { value: "Ivory Coast", text: "Tribal Group"},
  { value: "Jamaica", text: "National Front for the Liberation of Cuba (FLNC)"},
  { value: "Jamaica", text: "Jamaica Labor Party"},
  { value: "Jamaica", text: "Right-wing extremists"},
  { value: "Jamaica", text: "Gunmen"},
  { value: "Japan", text: "Chukakuha (Middle Core Faction)"},
  { value: "Japan", text: "Revolutionary Workers' Council (Kakurokyo)"},
  { value: "Japan", text: "East Asia Anti Japanese Armed Front"},
  { value: "Japan", text: "Aum Shinri Kyo"},
  { value: "Japan", text: 'Senki ("Battle Flag")'},
  { value: "Jordan", text: "Islamic State of Iraq and the Levant (ISIL)"},
  { value: "Jordan", text: "Popular Front for the Liberation of Palestine (PFLP)"},
  { value: "Jordan", text: "Abu Nidal Organization (ANO)"},
  { value: "Jordan", text: "Al-Qaida in Iraq"},
  { value: "Jordan", text: "Black September"},
  { value: "Kazakhstan", text: "Kazakhstan Liberation Army"},
  { value: "Kazakhstan", text: "Chechen Rebels"},
  { value: "Kazakhstan", text: "Soldiers of the Caliphate"},
  { value: "Kazakhstan", text: "Gunmen"},
  { value: "Kazakhstan", text: "Muslim extremists"},
  { value: "Kenya", text: "Al-Shabaab"},
  { value: "Kenya", text: "Mombasa Republican Council (MRC)"},
  { value: "Kenya", text: "Kenya African National Union (KANU)"},
  { value: "Kenya", text: "Mungiki Sect"},
  { value: "Kenya", text: "Merille Militia"},
  { value: "Kosovo", text: "Albanian extremists"},
  { value: "Kosovo", text: "Kosovo Liberation Army (KLA)"},
  { value: "Kosovo", text: "Gunmen"},
  { value: "Kosovo", text: "Rugovasit Group"},
  { value: "Kosovo", text: "Separatists"},
  { value: "Kuwait", text: "Hezbollah"},
  { value: "Kuwait", text: "Arab Revolution/Liberation Vanguard Organization"},
  { value: "Kuwait", text: "Muslim Fundamentalists"},
  { value: "Kuwait", text: "Muslim extremists"},
  { value: "Kuwait", text: "Palestinians"},
  { value: "Kyrgyzstan", text: "Islamic Movement of Uzbekistan (IMU)"},
  { value: "Kyrgyzstan", text: "Muslim extremists"},
  { value: "Kyrgyzstan", text: "Eastern Turkistan Islamic Movement (ETIM)"},
  { value: "Kyrgyzstan", text: "Uighur Separatists"},
  { value: "Laos", text: "Bandits"},
  { value: "Laos", text: "Free Democratic People's Government of Laos"},
  { value: "Laos", text: "Gunmen"},
  { value: "Latvia", text: "Fighters of Democratic Latvia"},
  { value: "Latvia", text: "Latvian Republic Volunteer Troops"},
  { value: "Latvia", text: "National Bolshevik Party (Partiya Natsionalnikh Bolshevikov - PNB)"},
  { value: "Lebanon", text: "Hezbollah"},
  { value: "Lebanon", text: "Palestinians"},
  { value: "Lebanon", text: "Palestine Liberation Organization (PLO)"},
  { value: "Lebanon", text: "Islamic State of Iraq and the Levant (ISIL)"},
  { value: "Lebanon", text: "Al-Nusrah Front"},
  { value: "Lesotho", text: "Lesotho Liberation Army (LLA)"},
  { value: "Lesotho", text: "Opposition Militants"},
  { value: "Liberia", text: "Liberians United for Reconciliation and Democracy (LURD)"},
  { value: "Liberia", text: "National Patriotic Front of Liberia (NPFL)"},
  { value: "Liberia", text: "Civil War Veterans"},
  { value: "Liberia", text: "Liberian Rebel Group"},
  { value: "Liberia", text: "National Democratic Front of Liberia"},
  { value: "Libya", text: "Tripoli Province of the Islamic State"},
  { value: "Libya", text: "Barqa Province of the Islamic State"},
  { value: "Libya", text: "Muslim extremists"},
  { value: "Libya", text: "Ansar al-Sharia (Libya)"},
  { value: "Libya", text: "Haftar Militia"},
  { value: "Lithuania", text: "Lithuanian Land Guard"},
  { value: "Luxembourg", text: "New Armenian Resistance"},
  { value: "Macau", text: "14 K Triad"},
  { value: "Macedonia", text: "National Liberation Army (NLA) (Macedonia)"},
  { value: "Macedonia", text: "Albanian extremists"},
  { value: "Macedonia", text: "Kosovo Liberation Army (KLA)"},
  { value: "Macedonia", text: "Albanian National Army (ANA)"},
  { value: "Macedonia", text: "Army of the Republic of Ilirida"},
  { value: "Madagascar", text: "Anti-Government Demonstrators"},
  { value: "Madagascar", text: "Defenders of the Nation's Sovereignty"},
  { value: "Madagascar", text: "Didier Ratsiraka's Militia"},
  { value: "Madagascar", text: "Militant Movement for Madagascan Socialism (MMSM)"},
  { value: "Malawi", text: "Anti-government rioters"},
  { value: "Malawi", text: "Young Pioneers"},
  { value: "Malaysia", text: "Abu Sayyaf Group (ASG)"},
  { value: "Malaysia", text: "Al-Ma'unah"},
  { value: "Malaysia", text: "Communist Party of Malaysia- Marxist-Leninist"},
  { value: "Malaysia", text: "Communists"},
  { value: "Malaysia", text: "Islamic State of Iraq and the Levant (ISIL)"},
  { value: "Maldives", text: "Muslim extremists"},
  { value: "Mali", text: "Ansar al-Dine (Mali)"},
  { value: "Mali", text: "Al-Qaida in the Islamic Maghreb (AQIM)"},
  { value: "Mali", text: "Movement for Oneness and Jihad in West Africa (MUJAO)"},
  { value: "Mali", text: "Muslim extremists"},
  { value: "Mali", text: "Tuareg extremists"},
  { value: "Malta", text: "Turkish radicals"},
  { value: "Martinique", text: "Caribbean Revolutionary Alliance (ARC)"},
  { value: "Martinique", text: "22 May 1948"},
  { value: "Martinique", text: "Guadeloupe Liberation Army"},
  { value: "Martinique", text: "Yich Telga"},
  { value: "Mauritania", text: "Al-Qaida in the Islamic Maghreb (AQIM)"},
  { value: "Mauritania", text: "Polisario Front"},
  { value: "Mauritania", text: "Salafist Group for Preaching and Fighting (GSPC)"},
  { value: "Mexico", text: "23rd of September Communist League"},
  { value: "Mexico", text: "Zapatista National Liberation Army"},
  { value: "Mexico", text: "Popular Revolutionary Army (Mexico)"},
  { value: "Mexico", text: "Union of the People (UDP)"},
  { value: "Mexico", text: "Institutional Revolutionary Party (PRI)"},
  { value: "Moldova", text: "Dnestr Republic Separatists"},
  { value: "Moldova", text: "Dnester region guerrilas"},
  { value: "Moldova", text: "Dnestr Rebels"},
  { value: "Moldova", text: "Ethnic Russian Separatists"},
  { value: "Moldova", text: "Russian Militia"},
  { value: "Morocco", text: "Al-Adl Wal Ihsane"},
  { value: "Morocco", text: "Polisario Front"},
  { value: "Morocco", text: "Salafia Jihadia"},
  { value: "Morocco", text: "Al-Qaida in the Islamic Maghreb (AQIM)"},
  { value: "Morocco", text: "Egyptians"},
  { value: "Mozambique", text: "Mozambique National Resistance Movement (MNR)"},
  { value: "Mozambique", text: "Mozambique Liberation Front (FRELIMO)"},
  { value: "Mozambique", text: "Right-Wing Group"},
  { value: "Mozambique", text: "African National Congress (South Africa)"},
  { value: "Mozambique", text: "Anti-Communist rebels"},
  { value: "Myanmar", text: "Karen National Union"},
  { value: "Myanmar", text: "Kachin Independence Army (KIA)"},
  { value: "Myanmar", text: "Buddhist Monks"},
  { value: "Myanmar", text: "Ta'ang National Liberation Army (TNLA)"},
  { value: "Myanmar", text: "Rohingya extremists"},
  { value: "Namibia", text: "South-West Africa People's Organization (SWAPO)"},
  { value: "Namibia", text: "National Union for the Total Independence of Angola (UNITA)"},
  { value: "Namibia", text: "White Wolves"},
  { value: "Namibia", text: "African National Congress (South Africa)"},
  { value: "Namibia", text: "Angolan Defense Force"},
  { value: "Nepal", text: "Maoists"},
  { value: "Nepal", text: "Janatantrik Terai Mukti Morcha- Jwala Singh (JTMM-J)"},
  { value: "Nepal", text: "Communist Party of Nepal-Maoist (Baidya)"},
  { value: "Nepal", text: "Janatantrik Terai Mukti Morcha (JTMM)"},
  { value: "Nepal", text: "Communist Party of Nepal - Maoist (CPN-Maoist-Chand)"},
  { value: "Netherlands", text: "Kurdistan Workers' Party (PKK)"},
  { value: "Netherlands", text: "South Moluccans"},
  { value: "Netherlands", text: "Dev Sol"},
  { value: "Netherlands", text: "Irish Republican Army (IRA)"},
  { value: "Netherlands", text: "Revolutionary Anti-Racist Action"},
  { value: "New Caledonia", text: "Kanak Socialist National Liberation Front"},
  { value: "New Caledonia", text: "Kanak Separatists"},
  { value: "New Caledonia", text: "Kanakas"},
  { value: "New Caledonia", text: "National Committee Against Independence (CNCI)"},
  { value: "New Caledonia", text: "Independence Advocates"},
  { value: "New Hebrides", text: "Secessionists"},
  { value: "New Zealand", text: "September 11"},
  { value: "New Zealand", text: "Animal Liberation Front (ALF)"},
  { value: "New Zealand", text: "Maori"},
  { value: "Nicaragua", text: "Nicaraguan Democratic Force (FDN)"},
  { value: "Nicaragua", text: "Sandinista National Liberation Front (FSLN)"},
  { value: "Nicaragua", text: "Nicaraguan Resistance"},
  { value: "Nicaragua", text: "Democratic Revolutionary Alliance (ARDE)"},
  { value: "Nicaragua", text: "Contras"},
  { value: "Niger", text: "Boko Haram"},
  { value: "Niger", text: "Tuareg Guerrillas"},
  { value: "Niger", text: "Al-Qaida in the Islamic Maghreb (AQIM)"},
  { value: "Niger", text: "Movement of Niger People for Justice (MNJ)"},
  { value: "Niger", text: "Tuareg extremists"},
  { value: "Nigeria", text: "Boko Haram"},
  { value: "Nigeria", text: "Fulani extremists"},
  { value: "Nigeria", text: "Movement for the Emancipation of the Niger Delta (MEND)"},
  { value: "Nigeria", text: "Niger Delta Avengers (NDA)"},
  { value: "Nigeria", text: "Ijaw extremists"},
  { value: "North Korea", text: "Kim Pyongnil Supporters"},
  { value: "Norway", text: "Kurdish Militants"},
  { value: "Norway", text: "Neo-Nazi extremists"},
  { value: "Norway", text: "Right-wing extremists"},
  { value: "Norway", text: "Anti-Iran Government Exiles"},
  { value: "Norway", text: "Anti-Semitic extremists"},
  { value: "Pakistan", text: "Tehrik-i-Taliban Pakistan (TTP)"},
  { value: "Pakistan", text: "Baloch Republican Army (BRA)"},
  { value: "Pakistan", text: "Muttahida Qami Movement (MQM)"},
  { value: "Pakistan", text: "Baloch Liberation Army (BLA)"},
  { value: "Pakistan", text: "Baloch Liberation Front (BLF)"},
  { value: "Panama", text: "20 December Movement (M-20)"},
  { value: "Panama", text: "Kuna Indians"},
  { value: "Panama", text: "Revolutionary Front for National Liberation"},
  { value: "Panama", text: "Panama Defense Force"},
  { value: "Panama", text: "Revolutionary Armed Forces of Colombia (FARC)"},
  { value: "Papua New Guinea", text: "Bougainville Revolutionary Army (BRA)"},
  { value: "Papua New Guinea", text: "Free Papua Movement (OPM-Organisasi Papua Merdeka)"},
  { value: "Papua New Guinea", text: "Lufa Tribesmen"},
  { value: "Papua New Guinea", text: "Political Group"},
  { value: "Papua New Guinea", text: "Separatists"},
  { value: "Paraguay", text: "Paraguayan People's Army (EPP)"},
  { value: "Paraguay", text: "Strikers"},
  { value: "Paraguay", text: "Croatian Nationalists"},
  { value: "Paraguay", text: "Ejercito Revolucionaria del Pueblo (ERP) (Argentina)"},
  { value: "Paraguay", text: "Liga Agraria Campesina"},
  { value: "People's Republic of the Congo", text: "Congolese Armed Patriotic Group"},
  { value: "People's Republic of the Congo", text: "Front for the Liberation of the Enclave of Cabinda (FLEC)"},
  { value: "Peru", text: "Shining Path (SL)"},
  { value: "Peru", text: "Tupac Amaru Revolutionary Movement (MRTA)"},
  { value: "Peru", text: "Rodrigo Franco Command"},
  { value: "Peru", text: "Narco-Terrorists"},
  { value: "Peru", text: "Terrorists"},
  { value: "Philippines", text: "New People's Army (NPA)"},
  { value: "Philippines", text: "Abu Sayyaf Group (ASG)"},
  { value: "Philippines", text: "Moro Islamic Liberation Front (MILF)"},
  { value: "Philippines", text: "Bangsamoro Islamic Freedom Movement (BIFM)"},
  { value: "Philippines", text: "Moro National Liberation Front (MNLF)"},
  { value: "Poland", text: "December 13 Independent Group"},
  { value: "Poland", text: "Anarchists"},
  { value: "Poland", text: "Anti-Immigrant extremists"},
  { value: "Poland", text: "GN-95"},
  { value: "Poland", text: "Neo-Nazi extremists"},
  { value: "Portugal", text: "Popular Forces of April 25"},
  { value: "Portugal", text: "Front For the Liberation of the Azores"},
  { value: "Portugal", text: "Justice Commandos for the Armenian Genocide"},
  { value: "Portugal", text: "Revolutionary Internationalist Solidarity"},
  { value: "Portugal", text: "Anarchists"},
  { value: "Qatar", text: "Iraqi extremists"},
  { value: "Qatar", text: "Organization of Soldiers of the Levant"},
  { value: "Qatar", text: "Palestinians"},
  { value: "Qatar", text: "The Organization for the Return of Legality"},
  { value: "Republic of Serbia", text: "Liberation Army for Presevo, Medvedja and Bujanovac (UCPMB)"},
  { value: "Republic of Serbia", text: "The Black Sun"},
  { value: "Republic of the Congo", text: "Ninjas"},
  { value: "Republic of the Congo", text: "Malitia-Pro Govt"},
  { value: "Republic of the Congo", text: "Mayi Mayi"},
  { value: "Republic of the Congo", text: "Presidential Movement (MP) Militiamen"},
  { value: "Republic of the Congo", text: "Supporters of Pascal Lissouba"},
  { value: "Rhodesia", text: "Zimbabwe African Nationalist Union (ZANU)"},
  { value: "Rhodesia", text: "Zimbabwe African People's Union"},
  { value: "Rhodesia", text: "Black Nationalists"},
  { value: "Rhodesia", text: "Zimbabwe Patriotic Front"},
  { value: "Rhodesia", text: "Zimbabwe Guerrillas"},
  { value: "Romania", text: "Bavarian Liberation Army"},
  { value: "Romania", text: "Black September II"},
  { value: "Russia", text: "Chechen Rebels"},
  { value: "Russia", text: "Caucasus Emirate"},
  { value: "Russia", text: "Muslim extremists"},
  { value: "Russia", text: "Armed Forces of the Chechen Republic of Ichkeria"},
  { value: "Russia", text: "Gunmen"},
  { value: "Rwanda", text: "Hutu extremists"},
  { value: "Rwanda", text: "Rwanda Patriotic Front (RPF)"},
  { value: "Rwanda", text: "Democratic Front for the Liberation of Rwanda (FDLR)"},
  { value: "Rwanda", text: "Inkotanyi"},
  { value: "Rwanda", text: "Armed People"},
  { value: "Saudi Arabia", text: "Houthi extremists (Ansar Allah)"},
  { value: "Saudi Arabia", text: "Islamic State of Iraq and the Levant (ISIL)"},
  { value: "Saudi Arabia", text: "Al-Qaida in the Arabian Peninsula (AQAP)"},
  { value: "Saudi Arabia", text: "Al-Qaida in Saudi Arabia"},
  { value: "Saudi Arabia", text: "Najd Province of the Islamic State"},
  { value: "Senegal", text: "Movement of Democratic Forces of Casamance"},
  { value: "Senegal", text: "Casamance Separatists"},
  { value: "Senegal", text: "Dioulas tribal group"},
  { value: "Senegal", text: "Liberation Front of the Senegalese People"},
  { value: "Senegal", text: "Mali students"},
  { value: "Serbia-Montenegro", text: "Albanian National Army (ANA)"},
  { value: "Serbia-Montenegro", text: "Zemun Clan"},
  { value: "Seychelles", text: "Mercenaries"},
  { value: "Sierra Leone", text: "Revolutionary United Front (RUF)"},
  { value: "Sierra Leone", text: "National Patriotic Front of Liberia (NPFL)"},
  { value: "Sierra Leone", text: "Rebels"},
  { value: "Sierra Leone", text: "Kamajor Hunters"},
  { value: "Sierra Leone", text: "Armed Forces Revolutionary Council (AFRC)"},
  { value: "Singapore", text: "Al-Zulfikar"},
  { value: "Singapore", text: "Japanese Red Army (JRA)"},
  { value: "Slovakia", text: "Neo-Nazi extremists"},
  { value: "Slovakia", text: "Right-wing extremists"},
  { value: "Solomon Islands", text: "Guadalcanal Liberation Army"},
  { value: "Solomon Islands", text: "Guadalcanal Liberation Front (GLF)"},
  { value: "Solomon Islands", text: "Isatabu Freedom Movement (IFM)"},
  { value: "Somalia", text: "Al-Shabaab"},
  { value: "Somalia", text: "Mujahideen Youth Movement (MYM)"},
  { value: "Somalia", text: "Hizbul al Islam (Somalia)"},
  { value: "Somalia", text: "Islamic Courts Union (ICU)"},
  { value: "Somalia", text: "Ahlu-sunah Wal-jamea (Somalia)"},
  { value: "South Africa", text: "African National Congress (South Africa)"},
  { value: "South Africa", text: "Inkatha Freedom Party (IFP)"},
  { value: "South Africa", text: "White extremists"},
  { value: "South Africa", text: "People Against Gangsterism and Drugs (PAGAD)"},
  { value: "South Africa", text: "White Wolves"},
  { value: "South Korea", text: "Student Radicals"},
  { value: "South Korea", text: "Students"},
  { value: "South Korea", text: "Anti-Park extremists"},
  { value: "South Korea", text: "Chondaehyop (Radical Student Coalition)"},
  { value: "South Korea", text: "Chonson Univ. students"},
  { value: "South Sudan", text: "Sudan People's Liberation Movement in Opposition (SPLM-IO)"},
  { value: "South Sudan", text: "Murle Tribe"},
  { value: "South Sudan", text: "David Yau Yau Militia"},
  { value: "South Sudan", text: "Lord's Resistance Army (LRA)"},
  { value: "South Sudan", text: "Mabanese Defence Forces"},
  { value: "South Yemen", text: "Popular Front for the Liberation of Palestine (PFLP)"},
  { value: "Soviet Union", text: "Armenian Guerrillas"},
  { value: "Soviet Union", text: "Armenian militants"},
  { value: "Soviet Union", text: "Black Berets"},
  { value: "Soviet Union", text: "Armenian extremists"},
  { value: "Soviet Union", text: "Armenian nationalists"},
  { value: "Spain", text: "Basque Fatherland and Freedom (ETA)"},
  { value: "Spain", text: "First of October Antifascist Resistance Group (GRAPO)"},
  { value: "Spain", text: "Terra Lliure"},
  { value: "Spain", text: "Free Galician People's Guerrilla Army"},
  { value: "Spain", text: "Revolutionary Patriotic Anti-Fascist Front (FRAP)"},
  { value: "Sri Lanka", text: "Liberation Tigers of Tamil Eelam (LTTE)"},
  { value: "Sri Lanka", text: "People's Liberation Front (JVP)"},
  { value: "Sri Lanka", text: "Tamils"},
  { value: "Sri Lanka", text: "Separatists"},
  { value: "Sri Lanka", text: "Vigilante Group"},
  { value: "St. Kitts and Nevis", text: "St. Kitts Nevis Labor Party"},
  { value: "St. Lucia", text: "Rastas"},
  { value: "Sudan", text: "Janjaweed"},
  { value: "Sudan", text: "Sudan People's Liberation Movement - North"},
  { value: "Sudan", text: "Lord's Resistance Army (LRA)"},
  { value: "Sudan", text: "Sudan People's Liberation Army (SPLA)"},
  { value: "Sudan", text: "Sudan Liberation Movement"},
  { value: "Suriname", text: "Brunswijk Jungle Commando"},
  { value: "Suriname", text: "National Liberation Union"},
  { value: "Suriname", text: "Surinamese Amerindians"},
  { value: "Suriname", text: "White Mercenaries"},
  { value: "Suriname", text: "Suriname Liberation Front"},
  { value: "Swaziland", text: "Umbane People's Liberation Army (Swaziland)"},
  { value: "Swaziland", text: "African National Congress (South Africa)"},
  { value: "Swaziland", text: "Mozambique National Resistance Movement (MNR)"},
  { value: "Swaziland", text: "People's United Democratic Movement (PUDEMO)"},
  { value: "Swaziland", text: "Swaziland Youth Congress (Swayoco)"},
  { value: "Sweden", text: "Croatian Nationalists"},
  { value: "Sweden", text: "Global Intifada"},
  { value: "Sweden", text: "Neo-Nazi extremists"},
  { value: "Sweden", text: "Anti-Immigrant extremists"},
  { value: "Sweden", text: "Iraqi extremists"},
  { value: "Switzerland", text: "Armenian Secret Army for the Liberation of Armenia"},
  { value: "Switzerland", text: "Revolutionary Perspective"},
  { value: "Switzerland", text: "Iberian Liberation Movement (MIL)"},
  { value: "Switzerland", text: "Justice Commandos for the Armenian Genocide"},
  { value: "Switzerland", text: "Krause Group"},
  { value: "Syria", text: "Islamic State of Iraq and the Levant (ISIL)"},
  { value: "Syria", text: "Al-Nusrah Front"},
  { value: "Syria", text: "Free Syrian Army"},
  { value: "Syria", text: "Muslim Brotherhood"},
  { value: "Syria", text: "Muslim extremists"},
  { value: "Taiwan", text: "Anti-Nuclear extremists"},
  { value: "Taiwan", text: "Chinese Illegal Immigrant"},
  { value: "Taiwan", text: "Democratic Progressive Party"},
  { value: "Taiwan", text: "Gang"},
  { value: "Taiwan", text: "Organized Crime"},
  { value: "Tajikistan", text: "People's Democratic Army"},
  { value: "Tajikistan", text: "Muslim Militants"},
  { value: "Tajikistan", text: "Rizvon Sadirov Group"},
  { value: "Tajikistan", text: "Armed People"},
  { value: "Tajikistan", text: "Gunmen"},
  { value: "Thailand", text: "Separatists"},
  { value: "Thailand", text: "Runda Kumpulan Kecil (RKK)"},
  { value: "Thailand", text: "Thai Islamic Militants"},
  { value: "Thailand", text: "Pattani United Liberation Organization (PULO)"},
  { value: "Thailand", text: "Muslim Separatists"},
  { value: "Togo", text: "Togolese Dissidents"},
  { value: "Togo", text: "Rebel Military Unit"},
  { value: "Togo", text: "Togolese Peoples Rally"},
  { value: "Trinidad and Tobago", text: "Taxi Drivers"},
  { value: "Trinidad and Tobago", text: "Professional Killers"},
  { value: "Trinidad and Tobago", text: "Coordination of the United Revolutionary Organization (CORU)"},
  { value: "Tunisia", text: "Okba Ibn Nafaa Brigade"},
  { value: "Tunisia", text: "Muslim extremists"},
  { value: "Tunisia", text: "Ansar al-Sharia (Tunisia)"},
  { value: "Tunisia", text: "Jund al-Khilafah (Tunisia)"},
  { value: "Tunisia", text: "Islamic State of Iraq and the Levant (ISIL)"},
  { value: "Turkey", text: "Kurdistan Workers' Party (PKK)"},
  { value: "Turkey", text: "Dev Sol"},
  { value: "Turkey", text: "Islamic State of Iraq and the Levant (ISIL)"},
  { value: "Turkey", text: "Turkish People's Liberation Army"},
  { value: "Turkey", text: "Devrimici Halk Kurtulus Cephesi (DHKP/C)"},
  { value: "Turkmenistan", text: "Gunmen"},
  { value: "Turkmenistan", text: "Taliban"},
  { value: "Uganda", text: "Lord's Resistance Army (LRA)"},
  { value: "Uganda", text: "Allied Democratic Forces (ADF)"},
  { value: "Uganda", text: "Uganda Freedom Movement (UFM)"},
  { value: "Uganda", text: "Uganda People's Army"},
  { value: "Uganda", text: "Holy Spirit Movement"},
  { value: "Ukraine", text: "Donetsk People's Republic"},
  { value: "Ukraine", text: "Luhansk People's Republic"},
  { value: "Ukraine", text: "Pro-Russia Militia"},
  { value: "Ukraine", text: "Cossack Separatists"},
  { value: "Ukraine", text: "Right Sector"},
  { value: "United Arab Emirates", text: "Abdullah Azzam Brigades"},
  { value: "United Arab Emirates", text: "Abu Nidal Organization (ANO)"},
  { value: "United Arab Emirates", text: "Al-Qaida in the Arabian Peninsula (AQAP)"},
  { value: "United Arab Emirates", text: "Iranians"},
  { value: "United Arab Emirates", text: "Palestinians"},
  { value: "United Kingdom", text: "Irish Republican Army (IRA)"},
  { value: "United Kingdom", text: "Protestant extremists"},
  { value: "United Kingdom", text: "Ulster Volunteer Force (UVF)"},
  { value: "United Kingdom", text: "Ulster Freedom Fighters (UFF)"},
  { value: "United Kingdom", text: "Irish National Liberation Army (INLA)"},
  { value: "United Republic of Tanzania", text: "The Association for Islamic Mobilisation and Propagation (UAMSHO)"},
  { value: "United Republic of Tanzania", text: "Al-Qaida"},
  { value: "United Republic of Tanzania", text: "Al-Shabaab"},
  { value: "United Republic of Tanzania", text: "Anti-United States extremists"},
  { value: "United Republic of Tanzania", text: "Bandits"},
  { value: "United States of America", text: "Anti-Abortion extremists"},
  { value: "United States of America", text: "Left-Wing Militants"},
  { value: "United States of America", text: "Fuerzas Armadas de Liberacion Nacional (FALN)"},
  { value: "United States of America", text: "New World Liberation Front (NWLF)"},
  { value: "United States of America", text: "Black Nationalists"},
  { value: "Uruguay", text: "Tupamaros (Uruguay)"},
  { value: "Uruguay", text: "Nationalist Patriotic Alliance (APN)"},
  { value: "Uruguay", text: "Anti-Semitic extremists"},
  { value: "Uruguay", text: "Artigas Guard Commando"},
  { value: "Uruguay", text: "Broad Front"},
  { value: "Uzbekistan", text: "Islamic Jihad Group (IJG)"},
  { value: "Uzbekistan", text: "Islamic Jihad Union (Uzbekistan)"},
  { value: "Vanuatu", text: "Vanuatu Mobile Force (VMF)"},
  { value: "Vatican City", text: "Grey Wolves"},
  { value: "Venezuela", text: "National Liberation Army of Colombia (ELN)"},
  { value: "Venezuela", text: "Red Flag (Venezuela)"},
  { value: "Venezuela", text: "Colombian Guerrillas"},
  { value: "Venezuela", text: "Revolutionary Armed Forces of Colombia (FARC)"},
  { value: "Venezuela", text: "Che Guevara Guerrillas"},
  { value: "West Bank", text: "Palestinians"},
  { value: "West Bank", text: "Palestinian Extremists"},
  { value: "West Bank", text: "Hamas (Islamic Resistance Movement)"},
  { value: "West Bank", text: "Al-Aqsa Martyrs Brigade"},
  { value: "West Bank", text: "Palestinian Islamic Jihad (PIJ)"},
  { value: "West Germany (FRG)", text: "Red Army Faction (RAF)"},
  { value: "West Germany (FRG)", text: "Revolutionary Cells"},
  { value: "West Germany (FRG)", text: "Baader-Meinhof Group"},
  { value: "West Germany (FRG)", text: "Irish Republican Army (IRA)"},
  { value: "West Germany (FRG)", text: "2nd of June Movement"},
  { value: "Western Sahara", text: "Polisario Front"},
  { value: "Yemen", text: "Al-Qaida in the Arabian Peninsula (AQAP)"},
  { value: "Yemen", text: "Houthi extremists (Ansar Allah)"},
  { value: "Yemen", text: "Tribesmen"},
  { value: "Yemen", text: "Southern Mobility Movement (Yemen)"},
  { value: "Yemen", text: "Adan-Abyan Province of the Islamic State"},
  { value: "Yugoslavia", text: "Kosovo Liberation Army (KLA)"},
  { value: "Yugoslavia", text: "Albanian extremists"},
  { value: "Yugoslavia", text: "Gunmen"},
  { value: "Yugoslavia", text: "Serbian guerrillas"},
  { value: "Yugoslavia", text: "Croatian Nationalists"},
  { value: "Zaire", text: "Congolese National Movement- Lumumba (MNCL)"},
  { value: "Zaire", text: "Hutu extremists"},
  { value: "Zaire", text: "Hutus Former Soldiers"},
  { value: "Zaire", text: "Congolese Liberation Party (PLC)"},
  { value: "Zaire", text: "Irish Republican Army (IRA)"},
  { value: "Zambia", text: "National Union for the Total Independence of Angola (UNITA)"},
  { value: "Zambia", text: "Mozambique National Resistance Movement (MNR)"},
  { value: "Zambia", text: "African National Congress (South Africa)"},
  { value: "Zambia", text: "Black Mambas"},
  { value: "Zimbabwe", text: "Zimbabwe African Nationalist Union (ZANU)"},
  { value: "Zimbabwe", text: "Supporters of Joshua Nkomo"},
  { value: "Zimbabwe", text: "Mozambique National Resistance Movement (MNR)"},
  { value: "Zimbabwe", text: "Movement for Democratic Change (MDC)"},
  { value: "Zimbabwe", text: "Zimbabwe African People's Union"}]
