var dropdown_options = [
  { value: "Afghanistan", text: "Taliban"},
  { value: "Afghanistan", text: "Haqqani Network"},
  { value: "Afghanistan", text: "Khorasan Chapter of the Islamic State"},
  { value: "Afghanistan", text: "Al-Qaida"},
  { value: "Afghanistan", text: "Hizb-I-Islami"},
  { value: "Algeria", text: "Algerian Islamic Extremists"},
  { value: "Algeria", text: "Armed Islamic Group (GIA)"},
  { value: "Algeria", text: "Islamic Salvation Front (FIS)"},
  { value: "Algeria", text: "Salafist Group for Preaching and Fighting (GSPC)"},
  { value: "Algeria", text: "Al-Qaida in the Islamic Maghreb (AQIM)"},
  { value: "Angola", text: "National Union for the Total Independence of Angola (UNITA)"},
  { value: "Angola", text: "Front for the Liberation of the Enclave of Cabinda (FLEC)"},
  { value: "Angola", text: "Popular Movement for the Liberation of Angola"},
  { value: "Angola", text: "Bandits"},
  { value: "Angola", text: "Popular Movement for the Liberation of Cabinda"},
  { value: "Argentina", text: "Montoneros (Argentina)"},
  { value: "Argentina", text: "Ejercito Revolucionaria del Pueblo (ERP) (Argentina)"},
  { value: "Argentina", text: "People's Revolutionary Organization"},
  { value: "Argentina", text: "Argentine Anticommunist Alliance (AAA)"},
  { value: "Argentina", text: "Che Guevara Brigade"},
  { value: "Australia", text: "Informal Anarchist Federation"},
  { value: "Austria", text: "Kurdistan Workers' Party (PKK)"},
  { value: "Austria", text: "Justice Commandos for the Armenian Genocide"},
  { value: "Austria", text: "Waltraud Boock Group"},
  { value: "Austria", text: "Abu Nidal Organization (ANO)"},
  { value: "Austria", text: "Black September"},
  { value: "Bahrain", text: "Hezbollah"},
  { value: "Bahrain", text: "Al-Ashtar Brigades"},
  { value: "Bangladesh", text: "Opposition Group"},
  { value: "Bangladesh", text: "Shanti Bahini - Peace Force"},
  { value: "Bangladesh", text: "Bangladesh Nationalist Party (BNP)"},
  { value: "Bangladesh", text: "Muslim Militants"},
  { value: "Bangladesh", text: "Awami League"},
  { value: "Belarus", text: "Friends of Freedom"},
  { value: "Belgium", text: "Communist Combattant Cells (CCC) (Belgium)"},
  { value: "Belgium", text: "Kurdistan Workers' Party (PKK)"},
  { value: "Belgium", text: "Justice Commandos for the Armenian Genocide"},
  { value: "Belgium", text: "Armenian Secret Army for the Liberation of Armenia"},
  { value: "Belgium", text: "International Revolutionary Action Group (GARI)"},
  { value: "Bolivia", text: "Tupac Katari Guerrilla Army (EGTK)"},
  { value: "Bolivia", text: "Bolivian Socialist Falange"},
  { value: "Bolivia", text: "Political Activists"},
  { value: "Bolivia", text: "Zarate Willka Armed Forces of Liberation"},
  { value: "Bolivia", text: "Nestor Paz Zamora Commission (CNPZ)"},
  { value: "Bosnia and Herzegovina", text: "Serbian guerrillas"},
  { value: "Bosnia and Herzegovina", text: "Muslim extremists"},
  { value: "Brazil", text: "Death Squad"},
  { value: "Brazil", text: "Communist Hunters Command (CCC)"},
  { value: "Brazil", text: "Landless Peasants' Movement (MST)"},
  { value: "Brazil", text: "Neo-Nazi extremists"},
  { value: "Brazil", text: "Popular Revolutionary Vanguard (VPR)"},
  { value: "Burkina Faso", text: "Al-Qaida in the Islamic Maghreb (AQIM)"},
  { value: "Burundi", text: "Hutu extremists"},
  { value: "Burundi", text: "Party for the Liberation of the Hutu People (PALIPEHUTU)"},
  { value: "Burundi", text: "National Liberation Front (FNL) (Burundi)"},
  { value: "Burundi", text: "Tutsi"},
  { value: "Burundi", text: "National Council for Defense of Democracy (NCDD)"},
  { value: "Cambodia", text: "Khmer Rouge"},
  { value: "Cambodia", text: "Cambodian Freedom Fighters (CFF)"},
  { value: "Cambodia", text: "Cambodian People's Party (CPP)"},
  { value: "Cambodia", text: "National United Front for an Independent, Neutral, Peaceful, and Cooperative Cambodia (FUNCINPEC)"},
  { value: "Cameroon", text: "Boko Haram"},
  { value: "Cameroon", text: "Africa Marine Commando"},
  { value: "Canada", text: "Armenian Secret Army for the Liberation of Armenia"},
  { value: "Canada", text: "Earth Liberation Front (ELF)"},
  { value: "Canada", text: "Front de Liberation du Quebec (FLQ)"},
  { value: "Central African Republic", text: "Anti-Balaka Militia"},
  { value: "Central African Republic", text: "Lord's Resistance Army (LRA)"},
  { value: "Central African Republic", text: "Seleka"},
  { value: "Central African Republic", text: "Convention of Patriots for Justice and Peace"},
  { value: "Central African Republic", text: "Popular Front for the Renaissance of the Central African Republic (FPRC)"},
  { value: "Chad", text: "Boko Haram"},
  { value: "Chad", text: "Rebels"},
  { value: "Chile", text: "Manuel Rodriguez Patriotic Front (FPMR)"},
  { value: "Chile", text: "Movement of the Revolutionary Left (MIR) (Chile)"},
  { value: "Chile", text: "United Popular Action Movement"},
  { value: "Chile", text: "People's Fatherland Movement"},
  { value: "Chile", text: "Extremists"},
  { value: "China", text: "Uighur Separatists"},
  { value: "China", text: "Koreans"},
  { value: "Colombia", text: "Revolutionary Armed Forces of Colombia (FARC)"},
  { value: "Colombia", text: "National Liberation Army of Colombia (ELN)"},
  { value: "Colombia", text: "M-19 (Movement of April 19)"},
  { value: "Colombia", text: "Narco-Terrorists"},
  { value: "Colombia", text: "Popular Liberation Army (EPL)"},
  { value: "Comoros", text: "Separatists"},
  { value: "Costa Rica", text: "Coordination of the United Revolutionary Organization (CORU)"},
  { value: "Costa Rica", text: "Student Front of the People"},
  { value: "Costa Rica", text: "Carlos Echeverria commando group"},
  { value: "Costa Rica", text: "Farabundo Marti National Liberation Front (FMLN)"},
  { value: "Costa Rica", text: "Revolutionary Commandos of Solidarity"},
  { value: "Croatia", text: "Serbian extremists"},
  { value: "Croatia", text: "Serbian guerrillas"},
  { value: "Cuba", text: "Raul Ernesto Cruz Leon, Salvadorian"},
  { value: "Cyprus", text: "Cyprus Turkish People's Movement"},
  { value: "Cyprus", text: "National Organization of Cypriot Fighters (EOKA)"},
  { value: "Czech Republic", text: "Revolutionary Cells Network (SRN)"},
  { value: "Democratic Republic of the Congo", text: "Allied Democratic Forces (ADF)"},
  { value: "Democratic Republic of the Congo", text: "Lord's Resistance Army (LRA)"},
  { value: "Democratic Republic of the Congo", text: "Democratic Front for the Liberation of Rwanda (FDLR)"},
  { value: "Democratic Republic of the Congo", text: "Mayi Mayi"},
  { value: "Democratic Republic of the Congo", text: "Patriotic Resistance Front in Ituri (FRPI)"},
  { value: "Denmark", text: "Anarchists"},
  { value: "Denmark", text: "Armenian Secret Army for the Liberation of Armenia"},
  { value: "Denmark", text: "Hezbollah"},
  { value: "Denmark", text: "Jihadi-inspired extremists"},
  { value: "Denmark", text: "Ninth of June Organization"},
  { value: "Dominica", text: "Anti-Government Group"},
  { value: "Dominican Republic", text: "Maximiliano Gomez Revolutionary Brigade"},
  { value: "Dominican Republic", text: "Popular Liberation Resistance Force"},
  { value: "Dominican Republic", text: "Dominican Popular Movement (MPD)"},
  { value: "Dominican Republic", text: "Tony El Pelou Band"},
  { value: "East Germany (GDR)", text: "Extraparliamentary Opposition (APO)"},
  { value: "East Germany (GDR)", text: "Internationalist Cells"},
  { value: "East Germany (GDR)", text: "Red Army Faction (RAF)"},
  { value: "Ecuador", text: "Alfaro Vive"},
  { value: "Ecuador", text: "Montoneros Patria Libre"},
  { value: "Ecuador", text: "People's Revolutionary Militias (MRP)"},
  { value: "Ecuador", text: "Pirates"},
  { value: "Ecuador", text: "National Liberation Army (Ecuador)"},
  { value: "Egypt", text: "Al-Gama'at al-Islamiyya (IG)"},
  { value: "Egypt", text: "Sinai Province of the Islamic State"},
  { value: "Egypt", text: "Muslim Militants"},
  { value: "Egypt", text: "Muslim extremists"},
  { value: "Egypt", text: "Ansar Bayt al-Maqdis (Ansar Jerusalem)"},
  { value: "El Salvador", text: "Farabundo Marti National Liberation Front (FMLN)"},
  { value: "El Salvador", text: "People's Liberation Forces (FPL)"},
  { value: "El Salvador", text: "People's Revolutionary Army (ERP) (El Salvador)"},
  { value: "El Salvador", text: "Death Squad"},
  { value: "El Salvador", text: "Armed Forces of National Resistance (FARN)"},
  { value: "Ethiopia", text: "Murle Tribe"},
  { value: "Ethiopia", text: "Eritrean Liberation Front"},
  { value: "Ethiopia", text: "Coalition for Unity and Democracy (CUD)"},
  { value: "Ethiopia", text: "Al-Shabaab"},
  { value: "Ethiopia", text: "Eritrean Peoples Liberation Front"},
  { value: "France", text: "Corsican National Liberation Front (FLNC)"},
  { value: "France", text: "Corsican National Liberation Front- Historic Channel"},
  { value: "France", text: "Resistenza"},
  { value: "France", text: "Action Directe"},
  { value: "France", text: "Armenian Secret Army for the Liberation of Armenia"},
  { value: "French Guiana", text: "Caribbean Revolutionary Alliance (ARC)"},
  { value: "French Guiana", text: "Separatists"},
  { value: "French Polynesia", text: "Anti-Nuclear extremists"},
  { value: "Georgia", text: "Supporters of Ex-President Gamsakhurdial"},
  { value: "Georgia", text: "Algeisk Wolves"},
  { value: "Georgia", text: "Georgian Militants"},
  { value: "Georgia", text: "South Ossetian Separatists"},
  { value: "Germany", text: "Neo-Nazi extremists"},
  { value: "Germany", text: "Kurdistan Workers' Party (PKK)"},
  { value: "Germany", text: "National Socialist Underground"},
  { value: "Germany", text: "Turkish Leftists"},
  { value: "Germany", text: "Dev Sol"},
  { value: "Ghana", text: "Farighan"},
  { value: "Greece", text: "November 17 Revolutionary Organization (N17RO)"},
  { value: "Greece", text: "Revolutionary People's Struggle (ELA)"},
  { value: "Greece", text: "Anarchists"},
  { value: "Greece", text: "Conspiracy of Cells of Fire"},
  { value: "Greece", text: "Revolutionary Struggle"},
  { value: "Guadeloupe", text: "Caribbean Revolutionary Alliance (ARC)"},
  { value: "Guadeloupe", text: "Armed Group for the Liberation of Guadeloupe (GLAG)"},
  { value: "Guadeloupe", text: "Guadeloupe Liberation Army"},
  { value: "Guatemala", text: "Guerrilla Army of the Poor (EGP)"},
  { value: "Guatemala", text: "Guatemalan National Revolutionary Unity (URNG)"},
  { value: "Guatemala", text: "Revolutionary Organization of People in Arms (ORPA)"},
  { value: "Guatemala", text: "Death Squad"},
  { value: "Guatemala", text: "31 January People's Front (FP-31)"},
  { value: "Haiti", text: "Cannibal Army"},
  { value: "Haiti", text: "Gunmen"},
  { value: "Haiti", text: "Aristide supporters"},
  { value: "Haiti", text: "Armed People"},
  { value: "Haiti", text: "Political Activists"},
  { value: "Honduras", text: "Lorenzo Zelaya Revolutionary Front (LZRF)"},
  { value: "Honduras", text: "Patriotic Morazanista Front (FPM)"},
  { value: "Honduras", text: "Cinchoneros Popular Liberation Movement"},
  { value: "Honduras", text: "Morazanist Front for the Liberation of Honduras (FMLH)"},
  { value: "Honduras", text: "Nicaraguan Democratic Force (FDN)"},
  { value: "India", text: "Communist Party of India - Maoist (CPI-Maoist)"},
  { value: "India", text: "Sikh Extremists"},
  { value: "India", text: "Maoists"},
  { value: "India", text: "United Liberation Front of Assam (ULFA)"},
  { value: "India", text: "Muslim Separatists"},
  { value: "Indonesia", text: "Free Aceh Movement (GAM)"},
  { value: "Indonesia", text: "Jemaah Islamiya (JI)"},
  { value: "Indonesia", text: "Muslim Militants"},
  { value: "Indonesia", text: "Free Papua Movement (OPM-Organisasi Papua Merdeka)"},
  { value: "Indonesia", text: "Opposition Group"},
  { value: "Iran", text: "Mujahedin-e Khalq (MEK)"},
  { value: "Iran", text: "Arab Separatists"},
  { value: "Iran", text: "Forqan Group"},
  { value: "Iran", text: "Armenian Secret Army for the Liberation of Armenia"},
  { value: "Iran", text: "Jundallah (Iran)"},
  { value: "Iraq", text: "Islamic State of Iraq and the Levant (ISIL)"},
  { value: "Iraq", text: "Al-Qaida in Iraq"},
  { value: "Iraq", text: "Islamic State of Iraq (ISI)"},
  { value: "Iraq", text: "Asa'ib Ahl al-Haqq"},
  { value: "Iraq", text: "Gunmen"},
  { value: "Ireland", text: "Ulster Freedom Fighters (UFF)"},
  { value: "Ireland", text: "Irish Republican Army (IRA)"},
  { value: "Ireland", text: "Ulster Volunteer Force (UVF)"},
  { value: "Ireland", text: "Irish National Liberation Army (INLA)"},
  { value: "Ireland", text: "Loyalist Volunteer Forces (LVF)"},
  { value: "Israel", text: "Palestinians"},
  { value: "Israel", text: "Hamas (Islamic Resistance Movement)"},
  { value: "Israel", text: "Palestinian Islamic Jihad (PIJ)"},
  { value: "Israel", text: "Al-Aqsa Martyrs Brigade"},
  { value: "Israel", text: "Popular Front for the Liberation of Palestine (PFLP)"},
  { value: "Italy", text: "Red Brigades"},
  { value: "Italy", text: "Prima Linea"},
  { value: "Italy", text: "Armenian Secret Army for the Liberation of Armenia"},
  { value: "Italy", text: "Armed Proletarian Nuclei (NAP)"},
  { value: "Italy", text: "Baader-Meinhof Group"},
  { value: "Ivory Coast", text: "Gbagbo Loyalists"},
  { value: "Ivory Coast", text: "Federation of Students and Scholars of Cote d'Ivoire (FESCI)"},
  { value: "Jamaica", text: "National Front for the Liberation of Cuba (FLNC)"},
  { value: "Jamaica", text: "Right-wing extremists"},
  { value: "Japan", text: "Chukakuha (Middle Core Faction)"},
  { value: "Japan", text: "Revolutionary Workers' Council (Kakurokyo)"},
  { value: "Japan", text: "Aum Shinri Kyo"},
  { value: "Japan", text: "East Asia Anti Japanese Armed Front"},
  { value: "Japan", text: "Tribal Battlefront"},
  { value: "Jordan", text: "Popular Front for the Liberation of Palestine (PFLP)"},
  { value: "Jordan", text: "Islamic State of Iraq and the Levant (ISIL)"},
  { value: "Jordan", text: "Abu Nidal Organization (ANO)"},
  { value: "Jordan", text: "Al-Qaida in Iraq"},
  { value: "Jordan", text: "Black September"},
  { value: "Kazakhstan", text: "Kazakhstan Liberation Army"},
  { value: "Kazakhstan", text: "Soldiers of the Caliphate"},
  { value: "Kenya", text: "Al-Shabaab"},
  { value: "Kenya", text: "Islamic Party of Kenya (IPK)"},
  { value: "Kenya", text: "Mungiki Sect"},
  { value: "Kenya", text: "Popular Front for the Liberation of Palestine (PFLP)"},
  { value: "Kenya", text: "God's Oppressed Army"},
  { value: "Kosovo", text: "Albanian extremists"},
  { value: "Kosovo", text: "Kosovo Liberation Army (KLA)"},
  { value: "Kosovo", text: "Rugovasit Group"},
  { value: "Kuwait", text: "Hezbollah"},
  { value: "Kuwait", text: "Arab Revolution/Liberation Vanguard Organization"},
  { value: "Kuwait", text: "Muslim Fundamentalists"},
  { value: "Kuwait", text: "Palestinians"},
  { value: "Kyrgyzstan", text: "Islamic Movement of Uzbekistan (IMU)"},
  { value: "Lebanon", text: "Hezbollah"},
  { value: "Lebanon", text: "Palestinians"},
  { value: "Lebanon", text: "Palestine Liberation Organization (PLO)"},
  { value: "Lebanon", text: "Islamic State of Iraq and the Levant (ISIL)"},
  { value: "Lebanon", text: "16 January Organization for the Liberation of Tripoli"},
  { value: "Lesotho", text: "Lesotho Liberation Army (LLA)"},
  { value: "Libya", text: "Tripoli Province of the Islamic State"},
  { value: "Libya", text: "Barqa Province of the Islamic State"},
  { value: "Libya", text: "Muslim extremists"},
  { value: "Libya", text: "Ansar al-Sharia (Libya)"},
  { value: "Libya", text: "Haftar Militia"},
  { value: "Macau", text: "14 K Triad"},
  { value: "Macedonia", text: "National Liberation Army (NLA) (Macedonia)"},
  { value: "Malaysia", text: "Abu Sayyaf Group (ASG)"},
  { value: "Malaysia", text: "Communist Party of Malaysia- Marxist-Leninist"},
  { value: "Maldives", text: "Muslim extremists"},
  { value: "Mali", text: "Ansar al-Dine (Mali)"},
  { value: "Mali", text: "Al-Qaida in the Islamic Maghreb (AQIM)"},
  { value: "Mali", text: "Movement for Oneness and Jihad in West Africa (MUJAO)"},
  { value: "Mali", text: "Tuareg extremists"},
  { value: "Mali", text: "Azawad National Liberation Movement (MNLA)"},
  { value: "Martinique", text: "Caribbean Revolutionary Alliance (ARC)"},
  { value: "Mauritania", text: "Al-Qaida in the Islamic Maghreb (AQIM)"},
  { value: "Mauritania", text: "Polisario Front"},
  { value: "Mexico", text: "23rd of September Communist League"},
  { value: "Mexico", text: "Union of the People (UDP)"},
  { value: "Mexico", text: "Zapatista National Liberation Army"},
  { value: "Mexico", text: "Institutional Revolutionary Party (PRI)"},
  { value: "Mexico", text: "Pagan Sect of the Mountain"},
  { value: "Moldova", text: "Dnestr Republic Separatists"},
  { value: "Morocco", text: "Salafia Jihadia"},
  { value: "Morocco", text: "Polisario Front"},
  { value: "Morocco", text: "Al-Adl Wal Ihsane"},
  { value: "Mozambique", text: "Mozambique National Resistance Movement (MNR)"},
  { value: "Mozambique", text: "Right-Wing Group"},
  { value: "Myanmar", text: "Karen National Union"},
  { value: "Myanmar", text: "Buddhist Monks"},
  { value: "Myanmar", text: "Rohingya extremists"},
  { value: "Myanmar", text: "Ta'ang National Liberation Army (TNLA)"},
  { value: "Myanmar", text: "Karen Insurgents"},
  { value: "Namibia", text: "South-West Africa People's Organization (SWAPO)"},
  { value: "Namibia", text: "National Union for the Total Independence of Angola (UNITA)"},
  { value: "Namibia", text: "White Wolves"},
  { value: "Nepal", text: "Maoists"},
  { value: "Nepal", text: "Janatantrik Terai Mukti Morcha- Jwala Singh (JTMM-J)"},
  { value: "Nepal", text: "Janatantrik Terai Mukti Morcha- Goit (JTMM-G)"},
  { value: "Nepal", text: "Janatantrik Terai Mukti Morcha- Rajan Mukti (JTMM-R)"},
  { value: "Nepal", text: "Ranbir Sena"},
  { value: "Netherlands", text: "Kurdistan Workers' Party (PKK)"},
  { value: "Netherlands", text: "Actiefront Nationalistisch Nederland"},
  { value: "Netherlands", text: "Autonomy Front"},
  { value: "Netherlands", text: "Dev Sol"},
  { value: "Netherlands", text: "Down with Lubbers"},
  { value: "New Caledonia", text: "Kanak Socialist National Liberation Front"},
  { value: "New Caledonia", text: "National Committee Against Independence (CNCI)"},
  { value: "New Zealand", text: "September 11"},
  { value: "Nicaragua", text: "Nicaraguan Democratic Force (FDN)"},
  { value: "Nicaragua", text: "Sandinista National Liberation Front (FSLN)"},
  { value: "Nicaragua", text: "Nicaraguan Resistance"},
  { value: "Nicaragua", text: "Democratic Revolutionary Alliance (ARDE)"},
  { value: "Nicaragua", text: "Contras"},
  { value: "Niger", text: "Boko Haram"},
  { value: "Niger", text: "Movement of Niger People for Justice (MNJ)"},
  { value: "Niger", text: "Islamist extremists"},
  { value: "Niger", text: "Al-Qaida in the Islamic Maghreb (AQIM)"},
  { value: "Niger", text: "Saharan Revolutionary Armed Front (FARS)"},
  { value: "Nigeria", text: "Boko Haram"},
  { value: "Nigeria", text: "Fulani extremists"},
  { value: "Nigeria", text: "Movement for the Emancipation of the Niger Delta (MEND)"},
  { value: "Nigeria", text: "Niger Delta Avengers (NDA)"},
  { value: "Nigeria", text: "Ijaw extremists"},
  { value: "Norway", text: "Kurdish Militants"},
  { value: "Pakistan", text: "Tehrik-i-Taliban Pakistan (TTP)"},
  { value: "Pakistan", text: "Muttahida Qami Movement (MQM)"},
  { value: "Pakistan", text: "Baloch Republican Army (BRA)"},
  { value: "Pakistan", text: "Lashkar-e-Jhangvi"},
  { value: "Pakistan", text: "Baloch Liberation Army (BLA)"},
  { value: "Panama", text: "20 December Movement (M-20)"},
  { value: "Panama", text: "Kuna Indians"},
  { value: "Panama", text: "Revolutionary Front for National Liberation"},
  { value: "Panama", text: "Anti-Government Demonstrators"},
  { value: "Panama", text: "Columbia PM"},
  { value: "Papua New Guinea", text: "Bougainville Revolutionary Army (BRA)"},
  { value: "Paraguay", text: "Paraguayan People's Army (EPP)"},
  { value: "Paraguay", text: "Strikers"},
  { value: "Peru", text: "Shining Path (SL)"},
  { value: "Peru", text: "Tupac Amaru Revolutionary Movement (MRTA)"},
  { value: "Peru", text: "Rodrigo Franco Command"},
  { value: "Peru", text: "Terrorists"},
  { value: "Peru", text: "Movement of the Revolutionary Left (MIR) (Peru)"},
  { value: "Philippines", text: "New People's Army (NPA)"},
  { value: "Philippines", text: "Abu Sayyaf Group (ASG)"},
  { value: "Philippines", text: "Moro Islamic Liberation Front (MILF)"},
  { value: "Philippines", text: "Moro National Liberation Front (MNLF)"},
  { value: "Philippines", text: "Bangsamoro Islamic Freedom Movement (BIFM)"},
  { value: "Poland", text: "December 13 Independent Group"},
  { value: "Portugal", text: "Popular Forces of April 25"},
  { value: "Portugal", text: "Front For the Liberation of the Azores"},
  { value: "Portugal", text: "Revolutionary Internationalist Solidarity"},
  { value: "Portugal", text: "Anarchists"},
  { value: "Portugal", text: "Justice Commandos for the Armenian Genocide"},
  { value: "Rhodesia", text: "Zimbabwe African Nationalist Union (ZANU)"},
  { value: "Rhodesia", text: "Black Nationalists"},
  { value: "Rhodesia", text: "Zimbabwe African People's Union"},
  { value: "Rhodesia", text: "Zimbabwe Guerrillas"},
  { value: "Rhodesia", text: "Zimbabwe People's Army (ZIPA)"},
  { value: "Russia", text: "Chechen Rebels"},
  { value: "Russia", text: "Caucasus Emirate"},
  { value: "Russia", text: "Armed Forces of the Chechen Republic of Ichkeria"},
  { value: "Russia", text: "Muslim extremists"},
  { value: "Russia", text: "Dagestani Shari'ah Jamaat"},
  { value: "Rwanda", text: "Hutu extremists"},
  { value: "Rwanda", text: "Rwanda Patriotic Front (RPF)"},
  { value: "Rwanda", text: "Democratic Front for the Liberation of Rwanda (FDLR)"},
  { value: "Saudi Arabia", text: "Houthi extremists (Ansar Allah)"},
  { value: "Saudi Arabia", text: "Al-Qaida in Saudi Arabia"},
  { value: "Saudi Arabia", text: "Al-Qaida in the Arabian Peninsula (AQAP)"},
  { value: "Saudi Arabia", text: "Al-Haramayn Brigades"},
  { value: "Saudi Arabia", text: "Generation of Arab Fury"},
  { value: "Senegal", text: "Movement of Democratic Forces of Casamance"},
  { value: "Seychelles", text: "Mercenaries"},
  { value: "Sierra Leone", text: "Revolutionary United Front (RUF)"},
  { value: "Sierra Leone", text: "National Patriotic Front of Liberia (NPFL)"},
  { value: "Somalia", text: "Al-Shabaab"},
  { value: "Somalia", text: "Hizbul al Islam (Somalia)"},
  { value: "Somalia", text: "Somali Salvation Front (SSF)"},
  { value: "Somalia", text: "Mujahideen Youth Movement (MYM)"},
  { value: "Somalia", text: "Rahanwein Resistance Army (RRA)"},
  { value: "South Africa", text: "African National Congress (South Africa)"},
  { value: "South Africa", text: "Inkatha Freedom Party (IFP)"},
  { value: "South Africa", text: "White extremists"},
  { value: "South Africa", text: "Economic Freedom Fighters"},
  { value: "South Africa", text: "People Against Gangsterism and Drugs (PAGAD)"},
  { value: "South Sudan", text: "Sudan People's Liberation Movement in Opposition (SPLM-IO)"},
  { value: "South Sudan", text: "Mabanese Defence Forces"},
  { value: "South Sudan", text: "Murle Tribe"},
  { value: "Soviet Union", text: "Armenian Guerrillas"},
  { value: "Spain", text: "Basque Fatherland and Freedom (ETA)"},
  { value: "Spain", text: "First of October Antifascist Resistance Group (GRAPO)"},
  { value: "Spain", text: "Terra Lliure"},
  { value: "Spain", text: "Free Galician People's Guerrilla Army"},
  { value: "Spain", text: "Revolutionary Patriotic Anti-Fascist Front (FRAP)"},
  { value: "Sri Lanka", text: "Liberation Tigers of Tamil Eelam (LTTE)"},
  { value: "Sri Lanka", text: "People's Liberation Front (JVP)"},
  { value: "Sri Lanka", text: "Tamils"},
  { value: "Sri Lanka", text: "Separatists"},
  { value: "Sri Lanka", text: "Terrorists"},
  { value: "Sudan", text: "Janjaweed"},
  { value: "Sudan", text: "Sudan People's Liberation Movement - North"},
  { value: "Sudan", text: "Lord's Resistance Army (LRA)"},
  { value: "Sudan", text: "Sudan People's Liberation Army (SPLA)"},
  { value: "Sudan", text: "Tribesmen"},
  { value: "Suriname", text: "Brunswijk Jungle Commando"},
  { value: "Suriname", text: "National Liberation Union"},
  { value: "Sweden", text: "Croatian Nationalists"},
  { value: "Sweden", text: "Global Intifada"},
  { value: "Sweden", text: "Turkish separatists (probably Kurds)"},
  { value: "Switzerland", text: "Armenian Secret Army for the Liberation of Armenia"},
  { value: "Switzerland", text: "Revolutionary Perspective"},
  { value: "Switzerland", text: "Iberian Liberation Movement (MIL)"},
  { value: "Switzerland", text: "Ninth of June Organization"},
  { value: "Syria", text: "Islamic State of Iraq and the Levant (ISIL)"},
  { value: "Syria", text: "Muslim Brotherhood"},
  { value: "Syria", text: "Al-Nusrah Front"},
  { value: "Syria", text: "Free Syrian Army"},
  { value: "Syria", text: "Muslim extremists"},
  { value: "Taiwan", text: "Anti-Nuclear extremists"},
  { value: "Tajikistan", text: "People's Democratic Army"},
  { value: "Tajikistan", text: "Muslim Militants"},
  { value: "Thailand", text: "Separatists"},
  { value: "Thailand", text: "Runda Kumpulan Kecil (RKK)"},
  { value: "Thailand", text: "Thai Islamic Militants"},
  { value: "Thailand", text: "Pattani United Liberation Organization (PULO)"},
  { value: "Thailand", text: "Muslim Separatists"},
  { value: "Togo", text: "Togolese Dissidents"},
  { value: "Trinidad and Tobago", text: "Taxi Drivers"},
  { value: "Tunisia", text: "Ansar al-Sharia (Tunisia)"},
  { value: "Tunisia", text: "Islamic State of Iraq and the Levant (ISIL)"},
  { value: "Tunisia", text: "Hezbollah"},
  { value: "Tunisia", text: "Muslim extremists"},
  { value: "Tunisia", text: "Okba Ibn Nafaa Brigade"},
  { value: "Turkey", text: "Kurdistan Workers' Party (PKK)"},
  { value: "Turkey", text: "Dev Sol"},
  { value: "Turkey", text: "Turkish People's Liberation Army"},
  { value: "Turkey", text: "Islamic State of Iraq and the Levant (ISIL)"},
  { value: "Turkey", text: "Great Eastern Islamic Raiders Front (IBDA-C)"},
  { value: "Uganda", text: "Lord's Resistance Army (LRA)"},
  { value: "Uganda", text: "Allied Democratic Forces (ADF)"},
  { value: "Uganda", text: "Uganda Freedom Movement (UFM)"},
  { value: "Uganda", text: "Uganda People's Army"},
  { value: "Uganda", text: "Al-Shabaab"},
  { value: "Ukraine", text: "Donetsk People's Republic"},
  { value: "Ukraine", text: "Luhansk People's Republic"},
  { value: "Ukraine", text: "Donskoy Army"},
  { value: "Ukraine", text: "Cossack Separatists"},
  { value: "Ukraine", text: "Ukrainian Insurgent Army"},
  { value: "United Kingdom", text: "Irish Republican Army (IRA)"},
  { value: "United Kingdom", text: "Protestant extremists"},
  { value: "United Kingdom", text: "Ulster Volunteer Force (UVF)"},
  { value: "United Kingdom", text: "Ulster Freedom Fighters (UFF)"},
  { value: "United Kingdom", text: "Irish National Liberation Army (INLA)"},
  { value: "United Republic of Tanzania", text: "The Association for Islamic Mobilisation and Propagation (UAMSHO)"},
  { value: "United States of America", text: "Anti-Abortion extremists"},
  { value: "United States of America", text: "Fuerzas Armadas de Liberacion Nacional (FALN)"},
  { value: "United States of America", text: "Left-Wing Militants"},
  { value: "United States of America", text: "Jewish Defense League (JDL)"},
  { value: "United States of America", text: "New World Liberation Front (NWLF)"},
  { value: "Uruguay", text: "Tupamaros (Uruguay)"},
  { value: "Uruguay", text: "Nationalist Patriotic Alliance (APN)"},
  { value: "Uzbekistan", text: "Islamic Jihad Group (IJG)"},
  { value: "Vanuatu", text: "Vanuatu Mobile Force (VMF)"},
  { value: "Venezuela", text: "National Liberation Army of Colombia (ELN)"},
  { value: "Venezuela", text: "Red Flag (Venezuela)"},
  { value: "Venezuela", text: "Che Guevara Guerrillas"},
  { value: "Venezuela", text: "Colombian Guerrillas"},
  { value: "Venezuela", text: "M-19 (Movement of April 19)"},
  { value: "West Bank", text: "Palestinians"},
  { value: "West Bank", text: "Hamas (Islamic Resistance Movement)"},
  { value: "West Bank", text: "Palestinian Extremists"},
  { value: "West Bank", text: "Al-Aqsa Martyrs Brigade"},
  { value: "West Bank", text: "Palestine Liberation Organization (PLO)"},
  { value: "West Germany (FRG)", text: "Revolutionary Cells"},
  { value: "West Germany (FRG)", text: "Red Army Faction (RAF)"},
  { value: "West Germany (FRG)", text: "Baader-Meinhof Group"},
  { value: "West Germany (FRG)", text: "Irish Republican Army (IRA)"},
  { value: "West Germany (FRG)", text: "2nd of June Movement"},
  { value: "Yemen", text: "Al-Qaida in the Arabian Peninsula (AQAP)"},
  { value: "Yemen", text: "Houthi extremists (Ansar Allah)"},
  { value: "Yemen", text: "Tribesmen"},
  { value: "Yemen", text: "Southern Mobility Movement (Yemen)"},
  { value: "Yemen", text: "Sanaa Province of the Islamic State"},
  { value: "Yugoslavia", text: "Kosovo Liberation Army (KLA)"},
  { value: "Yugoslavia", text: "Albanian extremists"},
  { value: "Yugoslavia", text: "Gunmen"},
  { value: "Yugoslavia", text: "Neo-Nazi extremists"},
  { value: "Yugoslavia", text: "Serbian guerrillas"},
  { value: "Zaire", text: "Congolese National Movement- Lumumba (MNCL)"},
  { value: "Zambia", text: "National Union for the Total Independence of Angola (UNITA)"},
  { value: "Zambia", text: "African National Congress (South Africa)"},
  { value: "Zimbabwe", text: "Supporters of Joshua Nkomo"},
  { value: "Zimbabwe", text: "Zimbabwe African Nationalist Union (ZANU)"}]
